### ISSUE TITLE
C++ compilation fails on macOS with libcxx 15

### ISSUE THREAD

**Issue by saraedum** [conda-forge/libcxx-feedstock#111]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Since this update, I see some issues with packages compiling source code at runtime with [cppyy](https://github.com/conda-forge/cppyy-feedstock) on macOS. Here is an example:

```
  In file included from input_line_1:1:
  In file included from /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/new:94:
  In file included from /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/exception:85:
  In file included from /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/type_traits:485:
  /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/__type_traits/is_pod.h:29:38: error: no template named 'is_trivially_default_constructible'; did you mean 'is_nothrow_default_constructible'?
      : public integral_constant<bool, is_trivially_default_constructible<_Tp>::value   &&
```

The full log is here: https://github.com/flatsurf/e-antic/actions/runs/4333166222/jobs/7566119386 (expand `Run flatsurf/actions/show-logs@main` to see the actual errors.)

I don't understand what's going on here. How could the `type_traits` header be inconsistent like that?

### Installed packages

```shell
antic                     0.2.5                hfef3418_2    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arb                       2.23.0               h905a977_0    conda-forge
autoconf                  2.71            pl5321hed12c24_1    conda-forge
automake                  1.16.5          pl5321h694c41f_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
benchmark                 1.7.1                hf0c8a7f_0    conda-forge
boost-cpp                 1.81.0               h2942534_0    conda-forge
byexample                 10.4.0          py310h2ec42d9_1    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-compiler                1.5.2                hbf74d83_0    conda-forge
ca-certificates           2022.12.7            h033912b_0    conda-forge
cctools                   973.0.1             h76f1dac_11    conda-forge
cctools_osx-64            973.0.1             hcc6d90d_11    conda-forge
clang                     14.0.6               h694c41f_0    conda-forge
clang-14                  14.0.6          default_h55ffa42_0    conda-forge
clang_osx-64              14.0.6               h3113cd8_4    conda-forge
clangxx                   14.0.6          default_h55ffa42_0    conda-forge
clangxx_osx-64            14.0.6               h6f97653_4    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
compiler-rt               14.0.6               h613da45_0    conda-forge
compiler-rt_osx-64        14.0.6               hab78ec2_0    conda-forge
coreutils                 9.1                  h5eb16cf_0    conda-forge
cppyy                     2.4.2           py310h8adbfe9_0    conda-forge
cppyy-backend             1.14.10         py310ha23aa8a_0    conda-forge
cppyy-cling               6.27.1          py310h71e7e49_0    conda-forge
cpycppyy                  1.12.12         py310ha23aa8a_0    conda-forge
cxx-compiler              1.5.2                hb8565cd_0    conda-forge
gf2x                      1.3.0                hb2a7efb_2    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
icu                       70.1                 h96cf925_0    conda-forge
ld64                      609                 hc6ad406_11    conda-forge
ld64_osx-64               609                 hfd63004_11    conda-forge
libclang-cpp14            14.0.6          default_h55ffa42_0    conda-forge
libcxx                    15.0.7               h71dddab_0    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libflint                  2.9.0           hfd2f71f_ntl_100    conda-forge
libllvm14                 14.0.6               h5b596cc_1    conda-forge
libllvm9                  9.0.1           default_h2671707_7    conda-forge
libsqlite                 3.40.0               ha978bb4_0    conda-forge
libtool                   2.4.7                hf0c8a7f_0    conda-forge
libzlib                   1.2.13               hfd90126_4    conda-forge
llvm-openmp               15.0.7               h61d9ccf_0    conda-forge
llvm-tools                14.0.6               h5b596cc_1    conda-forge
m4                        1.4.18            haf1e3a3_1001    conda-forge
make                      4.3                  h22f3db7_1    conda-forge
mpfr                      4.1.0                h0f52abe_1    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
ntl                       11.4.3               h0ab3c2f_1    conda-forge
openssl                   3.0.8                hfd90126_0    conda-forge
perl                      5.32.1          2_h0d85af4_perl5    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pyte                      0.8.0                      py_0    conda-forge
python                    3.10.9          he7542f4_0_cpython    conda-forge
python_abi                3.10                    3_cp310    conda-forge
readline                  8.1.2                h3899abd_0    conda-forge
setuptools                67.4.0             pyhd8ed1ab_0    conda-forge
sigtool                   0.1.3                h88f4db0_0    conda-forge
tapi                      1100.0.11            h9ce4665_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
zstd                      1.5.2                hbc0c0cd_6    conda-forge
```

### Environment info

```shell
This is a macOS 11.7.4 as provided by GitHub's runners with mamba as configured by conda-incubator/setup-miniconda@v2 action.

I could also run conda info somehow in the CI if that's helpful.
```

**Comment by saraedum** [comment]
@isuruf, any idea what might be going on here?

**Comment by h-vetinari** [comment]
> I don't understand what's going on here. How could the `type_traits` header be inconsistent like that?

The headers upstream were granularized ([example](https://github.com/llvm/llvm-project/commit/b7aa9c4ac8e7a2736125109deeb0be8b1f41f852)), and it seems that libcxx 15 is missing the right header to use `is_trivially_default_constructible` in [`is_pod.h`](https://github.com/llvm/llvm-project/blob/llvmorg-15.0.7/libcxx/include/__type_traits/is_pod.h).

However, that branch only triggers if `#if __has_builtin(__is_pod)` is false, so I guess you could try using a newer compiler that has said builtin. I checked if this oversight was fixed upstream but it [looks](https://github.com/llvm/llvm-project/blob/release/16.x/libcxx/include/__type_traits/is_pod.h) like for LLVM 16, the fallback (for not having `__is_pod`) was removed completely. As such there's nothing obvious that we could backport, except of course we could just try to include the correct header.

Otherwise, you could raise an issue upstream and see what the libcxx people recommend (though given that there won't be any more releases for 15.x, I'm not sure how much attention it'll get; sorry that we were so far behind in getting libcxx 15 to conda-forge, otherwise we could have discovered this in a more timely fashion). Perhaps it's still interesting for them from a test-coverage POV.

**Comment by saraedum** [comment]
@h-vetinari thanks for the explanation :)

I am still a bit confused as to why I am the only one affected by this. The compiler I am using here is `cxx-compiler` which on macOS is clang-cxx 14 currently. This now pulls in libcxx 15.0.7. That combination is working fine in feedstocks I rebuilt in the past few days. What could be different in my application that makes this combination break?

**Comment by saraedum** [comment]
cc @wlav this seems to break the cppyy build for macOS on conda-forge.

**Comment by wlav** [comment]
May simply be that here, too, Clang9 is just way too old. Repo master is at Clang13. I'll push to get it released (as cppyy 3.0.0).

**Comment by saraedum** [comment]
Ok. Then this is unrelated to the installed cxx-compiler which makes sense. I guess we need make sure that cppyy forces `libcxx <15` on conda-forge until cppyy 3 is out.

**Comment by h-vetinari** [comment]
> May simply be that here, too, Clang9 is just way too old.

I had no idea your compiler was that old. Yes, that's way too old (and explains the missing built-in).

> Repo master is at Clang13.

Do you depend on specific details of individual llvm/clang versions? Because llvm 16 is almost out, and 13 is quite old itself already. Unless you really need to (which is rare), it'd be better to just use the default compiler version in conda-forge (currently 14, but only because some parts of the 15 stack were stuck for quite a while).

> I'll push to get it released (as cppyy 3.0.0).

Thanks!

**Comment by wlav** [comment]
> Do you depend on specific details of individual llvm/clang versions?

Yes, Cling has modifications made to Clang for interactive use, in particular to allow graceful recovery from failure. A lot, but not all, of these changes are being upstreamed into Clang (clang-repl, for the benefit of lldb), so future upgrades should come faster, as there will be fewer modifications. E.g. I believe, but haven't tried, that current Cling on Clang13 can use stock LLVM13 again. Another reason to be optimistic is that support for interactivity and JITing in Clang/LLVM itself is seeing lots of improvements, e.g. JITLink. Still, I depend on Cling to do these upgrades first, before getting support into cppyy and this will always be the case.

Note that other than parsing headers, Cling's Clang is linked internally, so it's actually possible to mix different LLVMs in the same process (e.g. Numba's llvmlite or Julia). Furthermore, the Cling folks are working on changing the incremental parsing to stop the parsing at the declarations only (in effect, make everything a forward declaration). The reason for this is performance: by not parsing definitions, headers load quicker, and only on use will definitions be parsed, reducing memory usage. Depending on how far they can push this, this will also increase the headers supported, as long as specific problematic definitions aren't used in the end.

**Comment by saraedum** [comment]
This should be fixed once https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/414 has been merged.
