### ISSUE TITLE
Issue updating from libcxx 14.0.6 to libcxx 16.0.6 with micromamba

### ISSUE THREAD

**Issue by mathomp4** [conda-forge/libcxx-feedstock#125]
### Comment:

I was trying to install a python stack today and it failed due to an issue with libcxx. To wit, I started with Miniconda3 23.5.2-0 for Intel Mac (Miniconda3-py311_23.5.2-0-MacOSX-x86_64.sh) and installed it. I then grabbed and installed [`micromamba`](https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html) as, for reasons I don't know, it's the only installer that works for me. 

I also have a `.condarc` that looks like:
```
channels:
  - conda-forge
  - defaults
channel_priority: strict
```
to favor conda-forge.

After that, I first did a `micromamba install libblas=*=*=mkl` which worked, then `micromamba install esmpy`. One of the things this calls for I guess is an update to libcxx:
```
  Upgrade:
─────────────────────────────────────────────────────────────────────────────

  - libcxx           14.0.6  h9765a3e_0              pkgs/main        991kB
  + libcxx           16.0.6  hd57cbcb_0              conda-forge     Cached
  - openssl           3.0.9  hca72f7f_0              pkgs/main          5MB
  + openssl           3.1.1  h8a1eda9_1              conda-forge     Cached
  - libcurl           8.1.1  hf20ceda_1              pkgs/main        369kB
  + libcurl           8.1.2  hbee3ae8_0              conda-forge     Cached
```
but:
```
critical libmamba filesystem error: in copy_file: Not a directory ["/Users/mathomp4/installed/Core/GEOSpyD/23.5.2-0_py3.11/2023-07-14/include/c++/v1/__string/char_traits.h"] ["/Users/mathomp4/micromamba/pkgs/libcxx-16.0.6-hd57cbcb_0/include/c++/v1/__string/char_traits.h"]
```
And this is true, that is a file, not a directory:
```
❯ file /Users/mathomp4/installed/Core/GEOSpyD/23.5.2-0_py3.11/2023-07-14/include/c++/v1/__string
/Users/mathomp4/installed/Core/GEOSpyD/23.5.2-0_py3.11/2023-07-14/include/c++/v1/__string: c program text, ASCII text
```

And if I look at llvm, [in 14.0.6 `__string` was a file](https://github.com/llvm/llvm-project/blob/llvmorg-14.0.6/libcxx/include/__string), but [in 16.0.6, it's a directory](https://github.com/llvm/llvm-project/tree/llvmorg-16.0.6/libcxx/include/__string).

Is there perhaps some special command I need to pass to my package installer to allow this to work? 

I can get it to work by using:
```bash
if [[ -f $INSTALLDIR/include/c++/v1/__string ]]
then
  rm $INSTALLDIR/include/c++/v1/__string
fi
```
before I know libcxx will be updated, but that seems ... not right to me.

**Comment by isuruf** [comment]
Could you open this in `mamba-org/mamba` repo?

**Comment by mathomp4** [comment]
@isuruf You think it's a failure of `mamba`? If so, do you know how `conda` handles this? The fact that you'd replace a file with a directory?

**Comment by isuruf** [comment]
Yeah, it's a failure of `micromamba`. I have no idea how `conda` handles this.

**Comment by mathomp4** [comment]
@isuruf Yeah. I just tried to do `conda install esmpy` on my machine and it just failed after about 10 minutes of trying to solve the dependency graph. At least `micromamba` can solve that in a few seconds. Okay. I'll close here and reopen there.
