### ISSUE TITLE
Enable `_LIBCPP_HARDENING_MODE_FAST`?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/libcxx-feedstock#136]
As of libcxx 18, the libcxx hardening got an extensive overhaul. The supported modes are now
* `_LIBCPP_HARDENING_MODE_NONE`
* `_LIBCPP_HARDENING_MODE_FAST`
* `_LIBCPP_HARDENING_MODE_EXTENSIVE`
* `_LIBCPP_HARDENING_MODE_DEBUG`

The goal of the fast mode is to do only critical checks and not cost (basically) any performance. This is the one that I think we should consider enabling, as users (and maintainers) would get better debug information rather than a crash.

Note that this also affects (by default) code built with libcxx, but _doesn't_ affect the ABI. [Details](https://libcxx.llvm.org/Hardening.html)

**Comment by h-vetinari** [comment]
@beckermr @jakirkham @xhochy @isuruf 
Any thoughts here?

**Comment by xhochy** [comment]
I'm fine with setting it to fast after reading the minimal documentation.
