### ISSUE TITLE
Getting back to 11.0 macOS deployment target in libcxx 17.0.6

### ISSUE THREAD

**Issue by ludwigschwardt** [conda-forge/libcxx-feedstock#157]
### Comment:

Hi, thanks for all the work you guys are putting into this!

As a newbie user, I'm naïvely trying to build Python wheels à la `cibuildwheel` but using `conda` as the environment. I'm aware of [this discussion](https://github.com/pypa/cibuildwheel/discussions/773) and Isuru's [suggestion](https://github.com/symengine/symengine-wheels#repository-to-build-wheels). I'm going down this foolish route thanks to Boost.Python...

All my conda libraries have 11.0 deployment targets on arm64 (as cibuildwheel likes it) except for libcxx 17.0.6 he7857fb_1, which is now on 12.0. This upsets `delocate-wheel`.

I've looked at #154 for more insight. If I try to install the alternate version (h5a255bb_1) with label `libcxx_macos_lt_12`, conda complains that `package libcxx-17.0.6-h5a255bb_1 has constraint __osx <12 conflicting with __osx-13.6.7-0`. This is fair enough, although I had hoped that this label would refer to deployment target and not actual OS version.

Am I using the `libcxx_macos_lt_12` label wrong?

The alternative is to just grin and bear the minimum OS version of 12.0 in my wheels (not so bad either).

Or maybe this is a complete wild goose chase?  😅

**Comment by isuruf** [comment]
See https://github.com/conda-forge/libcxx-feedstock/pull/154#discussion_r1651881651

**Comment by ludwigschwardt** [comment]
Excellent!

**Comment by jakirkham** [comment]
Think you need the `build/number` `0` of `17.0.6` for macOS 10.13

xref: https://github.com/conda-forge/libcxx-feedstock/pull/154#discussion_r1651892371

@h-vetinari (in case I've misunderstood something)

**Comment by ludwigschwardt** [comment]
Thanks, that's exactly what I ended up doing. I'm glad to hear it's a temporary issue.
