### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range

### ISSUE THREAD

**Issue by jschueller** [conda-forge/libcxx-feedstock#29]
Hello,

I'm investigating a migration PR for openturns (https://github.com/conda-forge/openturns-feedstock/pull/66) and some osx/clangxx jobs (https://travis-ci.org/conda-forge/openturns-feedstock/jobs/447025412) use libcxx 4.0.1:

```
...
clang:           4.0.1-h662ec87_0           conda-forge/label/gcc7
clang_osx-64:    4.0.1-h1ce6c1d_11          conda-forge/label/gcc7
clangxx:         4.0.1-hc9b4283_0           defaults              
    clangxx_osx-64:  4.0.1-h22b1bf0_11          defaults              
libcxx:          4.0.1-h579ed51_0                       conda-forge/label/gcc7
libcxxabi:       4.0.1-hebd6815_0                       conda-forge/label/gcc7
...
llvm:            4.0.1-hc748206_0           conda-forge/label/gcc7
    llvm-lto-tapi:   4.0.1-h6701bc3_0           conda-forge/label/gcc7
```

The reason my build fails comes down to the out_of_bound exception not being caught properly. On this example it goes to the catch(...) path instead of the first catch.:
```
std::vector<double> mesh(3);
try {
    double v = mesh.at(8);
    std::cout << "v=" << v << std::endl; 
  }
  catch(std::out_of_range & ex) {
    std::cout << "CAUGHT out_of_range="<<ex.what() << std::endl; 
  }
  catch(...) {
    std::cout << "CAUGHT*" << std::endl; 
  throw;
  }
```

If not caught it errors out with the message:
```libc++abi.dylib: terminating with uncaught exception of type std::out_of_range```

**Comment by jschueller** [comment]
seems something wrong in the link step, if I set LDFLAGS="", it will work for my test executable, but not for a python module, maybe because of the "-undefined dynamic_lookup" we have to use for these, some libcxx symbols get weark referenced or something ?

**Comment by mingwandroid** [comment]
I cannot reproduce this, something else has gone wrong, probably you're linking to the system libc++ here instead. This is my failed reproducer:

```
cat ~/issue-29.cpp
#include <ostream>
#include <iostream>
#include <vector>

using namespace std;

int main() {
std::vector<double> mesh(3);
try {
    double v = mesh.at(8);
    std::cout << "v=" << v << std::endl;
  }
  catch(std::out_of_range & ex) {
    std::cout << "CAUGHT out_of_range="<<ex.what() << std::endl;
  }
  catch(...) {
    std::cout << "CAUGHT*" << std::endl;
  throw;
  }
}
```

```
CONDA_BUILD_SYSROOT=/opt/MacOSX10.9.sdk $CXX ~/issue-29.cpp
./a.out 
CAUGHT out_of_range=vector
```

**Comment by mingwandroid** [comment]
I also tested this with `CONDA_BUILD_SYSROOT=/opt/MacOSX10.10.sdk` and `CONDA_BUILD_SYSROOT=/opt/MacOSX10.9.sdk` without any issue. Our macOS compilers are pretty solid guys.

**Comment by mingwandroid** [comment]
libc++ is installed into the host prefix by virtue of strong run_exports. It should be in the build prefix too (which it always is), as that's where the compiler needs to find it (due to relative path calculations etc).

**Comment by mingwandroid** [comment]
Again, I see no problem:

```
tar -xf /opt/MacOSX10.9.sdk.tar.xz 
CONDA_BUILD_SYSROOT=$PWD/MacOSX10.9.sdk $CXX ~/issue-29.cpp
 ./a.out 
CAUGHT out_of_range=vector
```

**Comment by isuruf** [comment]
@mingwandroid can you try adding `-Wl,-rpath,$CONDA_PREFIX/lib -L$CONDA_PREFIX/lib` at the end?

**Comment by mingwandroid** [comment]
ah ok, missed that, thanks.

**Comment by mingwandroid** [comment]
the PWD bit isn't relevant it seems, but yes, something's up.

**Comment by mingwandroid** [comment]
I take back the solidity comment, this is a pretty bad bug!

**Comment by mingwandroid** [comment]
We're updating to 7.0.0 soon, I'll make sure it's free from this when I get onto that.

**Comment by isuruf** [comment]
Fixing the lines at https://github.com/llvm-mirror/libcxx/blob/9bc5d8e1baf71c4094630de591130fde873abd39/lib/CMakeLists.txt#L159-L169 to use the libc++abi from conda fixes this issue for me.

**Comment by isuruf** [comment]
@mingwandroid, @msarahan, if I send you a patch, would you be able to build 4.0.1 with that patch for us please?

**Comment by mingwandroid** [comment]
For sure, I'll build it asap and put it my test channel.

**Comment by jschueller** [comment]
You are awesome guys.

**Comment by isuruf** [comment]
@mingwandroid, see https://github.com/isuruf/aggregate/commit/1232059bc1dd1b60a2fee0dd90d17ba30adeb744
I haven't built clang and llvm as a single project, so not sure if this will work. If you don't see
```
WARNING (libcxx,lib/libc++.1.0.dylib): Needed DSO /usr/lib/libc++abi.dylib not found in any CDT/compiler package, nor the whitelist?!
```
then it works.

**Comment by isuruf** [comment]
Updated patch at https://github.com/isuruf/aggregate/commit/e39ae53356a163af8cc8bbca76d222a817f381c1

**Comment by mingwandroid** [comment]
Gah, ok!

**Comment by jschueller** [comment]
Thanks for the patch, how can I test the new 7.0 binaries ?

**Comment by isuruf** [comment]
@jschueller, you can't do it yet in conda-build. You can test by installing clangdev, libcxx from conda-forge.

**Comment by jschueller** [comment]
Ok

**Comment by mingwandroid** [comment]
I made test builds, but I didn't actually list the patch (I had to merge it manually). Unsurprisingly they didn't work.

New ones in progress.

**Comment by mingwandroid** [comment]
Ok, I uploaded the rebuilt compilers to rdonnelly. This test passes now.

@isuruf, do you have any reference to this fix or did you develop it yourself?

**Comment by isuruf** [comment]
I made the patch. I'll submit it upstream soon. (Once I figure out how to contribute and use phabricator)

**Comment by mingwandroid** [comment]
@isuruf, given that `/usr/lib/libc++.dylib` is getting used without `-Wl,-rpath,$CONDA_PREFIX/lib` I now agree that we need to add that to the activate scripts.

**Comment by isuruf** [comment]
> given that /usr/lib/libc++.dylib is getting used without -Wl,-rpath,$CONDA_PREFIX/lib

Is it? `CONDA_BUILD_SYSROOT=$PWD/MacOSX10.9.sdk $CXX test.cpp` doesn't use `/usr/lib/libc++.dylib`

**Comment by mingwandroid** [comment]
Run then with:

`DYLD_PRINT_LIBRARIES=1 ./a.out`

.. and see what you can see. What's happening is the exe has no rpath, but libcxx is identified via one, so the system default value is used.

**Comment by isuruf** [comment]
Got it. Thanks for the explanation.

I sent the patch upstream. https://reviews.llvm.org/D53797

**Comment by jschueller** [comment]
the build is ok with your patch/new binary: https://travis-ci.org/conda-forge/openturns-feedstock/jobs/447324424 : )

**Comment by jschueller** [comment]
Hi, seems you uploaded the patched version in defaults, but not in conda-forge. What is preventing to update the conda forge version as well ?

**Comment by mingwandroid** [comment]
I dislike duplication.

**Comment by mingwandroid** [comment]
If you need our compilers on conda-forge to avoid channel incompatibility issues then I'm fine with that. Using the same ones is important and a rebuild of our recipe on cf infra may be possible but it'd be tricky and would risk making compilers that aren't compatible with ours.

**Comment by SylvainCorlay** [comment]
> If you need our compilers on conda-forge to avoid channel incompatibility issues then I'm fine with that. Using the same ones is important and a rebuild of our recipe on cf infra may be possible but it'd be tricky and would risk making compilers that aren't compatible with ours.

Would it make sense for the same built recipe to be pushed on the conda-forge channel even if not from a conda-forge feedstock?

**Comment by isuruf** [comment]
@jschueller, @ocefpaf copied the defaults ones to conda-forge this morning.

**Comment by jschueller** [comment]
Or, could a new version of libcxx from this feedstock be published with the same patch ?

**Comment by isuruf** [comment]
@jschueller, I restarted the openturns builds. Should work fine now

**Comment by jschueller** [comment]
oh I did not see it was published, in that case we're okay

**Comment by jschueller** [comment]
@isuruf the new libcxx package still does not get picked up

**Comment by isuruf** [comment]
Hmm, that's clearly wrong. `4.0.1-h579ed51_0` is in `broken` label`, but it's getting picked up. Something's wrong with the conda solver

**Comment by isuruf** [comment]
Ignore my last comment. It's a travis-ci thing. Log of the previous run is merged with the new one

**Comment by jschueller** [comment]
Yup, it went fine. Thank you guys.
