### ISSUE TITLE
Currently Labeled as Broken?

### ISSUE THREAD

**Issue by insertinterestingnamehere** [conda-forge/libcxx-feedstock#35]
Issue: On Anaconda Cloud all the builds for this package are now labeled as "broken" but I've been unable to find any explanation as to why? Is this intentional? What needs to be fixed?

**Comment by jessemapel** [comment]
I am also curious about this.

**Comment by jessemapel** [comment]
@SylvainCorlay
@inducer
@isuruf
@jakirkham
@mattwala

Any updates on this?

**Comment by isuruf** [comment]
cc @ocefpaf

**Comment by ocefpaf** [comment]
Sorry for the confusion. We probably removed them while fixing the compiler vendorizing problem. See https://anaconda.org/anaconda/libcxx/files https://conda-forge.org/docs/user/tipsandtricks.html for more info.

I'll re-add them in a minute.

**Comment by isuruf** [comment]
@ocefpaf, there were packages that were already broken. Please don't re-add them.

**Comment by isuruf** [comment]
@ocefpaf, do you remember which ones were already broken when you marked all packages as broken?

**Comment by ocefpaf** [comment]
Done! Hopefully this won't bring any incompatibilities with the packages that are built using `libcxx` from `defaults`.

**Comment by ocefpaf** [comment]
> @ocefpaf, do you remember which ones were already broken when you marked all packages as broken?

That is impossible to know. I don't think we had that information.

If anyone from the @conda-forge/libcxx team knows please ping me to re-remove them.
Or we can just keep the latest version, what do you think?

**Comment by isuruf** [comment]
Latest version is broken on osx if I remember correctly.

**Comment by ocefpaf** [comment]
> Latest version is broken on osx if I remember correctly.

Thanks. Looks like you already took care of it.

**Comment by insertinterestingnamehere** [comment]
Great, thanks for taking care of this! I'll go ahead and close the issue.

**Comment by jessemapel** [comment]
@isuruf What's broken with the OSX builds? Is there an issue or something somewhere about that?

**Comment by isuruf** [comment]
@jessemapel, libcxx 6.0.0 was built with system compilers and 7.0.0 with the anaconda compilers. with 7.0.0, there was a cyclic dependency because llvmdev and clangdev had a dependency on libcxx from defaults and libcxx needed llvmdev and clangdev to be built. I tried working around this with a hack and this didn't work as intended and there were segfaults in downstream packages
