### ISSUE TITLE
build error with clang/llvm 11 using libcxx 12 on osx

### ISSUE THREAD

**Issue by beckermr** [conda-forge/libcxx-feedstock#76]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

See this CI job which has the env info but not a great error message: https://github.com/conda-forge/stackvana-afw-feedstock/pull/22/checks?check_run_id=2630727543

**Comment by h-vetinari** [comment]
This issue is going on two years old, and the logs are obviously gone. C-f also moved to LLVM 14 in the meantime, so I'm closing this as stale
