### ISSUE TITLE
Segfault with Boost.Serialization on conda OSX

### ISSUE THREAD

**Issue by jcarpent** [conda-forge/libcxx-feedstock#77]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: 
I'm using boost-cpp within conda for serialization purposes. 
Yet, I obtain a segfault even with this simple snippet:
```
#include <boost/archive/text_oarchive.hpp>
#include <fstream>
#include <string>

int main()
{
  std::string filename = "output.txt";
  std::ofstream ofs(filename.c_str());
  boost::archive::text_oarchive oa(ofs);
  return -1;
}
```
compiled with:
```
clang++ test.cpp -o test -I $CONDA_PREFIX/include $CONDA_PREFIX/lib/libboost_serialization.dylib -Wl,-rpath,$CONDA_PREFIX/lib
```
Interestingly, there is no bug when using boost provided by Brew for instance.
Do you know where this bug is coming from?
Do you have some hints on how to solve this issue?

Thanks in advance for your kind help,
Best,

Justin
<br/>
Environment (<code>conda list</code>):
<details>

```
boost-cpp                 1.76.0               hff03dee_1    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
certifi                   2020.12.5        py38h50d1736_1    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
libcxx                    12.0.0               habf9029_0    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
openssl                   1.1.1k               h0d85af4_0    conda-forge
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
python                    3.8.10          h3a889e0_1_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
setuptools                49.6.0           py38h50d1736_3    conda-forge
sqlite                    3.35.5               h44b9ce1_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.5.0                h582d3a0_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : pin-test
    active env location : /usr/local/Caskroom/miniconda/4.6.14/miniconda3/envs/pin-test
            shell level : 1
       user config file : /Users/jucarpen/.condarc
 populated config files : /Users/jucarpen/.condarc
          conda version : 4.10.1
    conda-build version : 3.18.11
         python version : 3.7.3.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/Caskroom/miniconda/4.6.14/miniconda3  (writable)
      conda av data dir : /usr/local/Caskroom/miniconda/4.6.14/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/Caskroom/miniconda/4.6.14/miniconda3/pkgs
                          /Users/jucarpen/.conda/pkgs
       envs directories : /usr/local/Caskroom/miniconda/4.6.14/miniconda3/envs
                          /Users/jucarpen/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.7.3 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 660720:21076
             netrc file : None
           offline mode : False
```
</details>

**Comment by isuruf** [comment]
Thanks for the test case. As a workaround for now, you can do `conda install libcxx=11`.

**Comment by jcarpent** [comment]
@isuruf Thanks a lot for this quick answer. I just confirm this is well working on my side.

**Comment by h-vetinari** [comment]
@isuruf, cool that you added this test in https://github.com/conda-forge/libcxx-testing-feedstock/pull/1. Would it make sense to add https://github.com/conda-forge/libcxx-testing-feedstock as a `downstream` test on this feedstock?

**Comment by h-vetinari** [comment]
This can be closed I believe

**Comment by erykoff** [comment]
@isuruf Oh my.  It seems that this test code is segfaulting again on MacOS 12 Monterey with clangxx=11, libcxx=11.  Any thoughts?

**Comment by isuruf** [comment]
Which libc++ version is MacOS 12 shipping?

**Comment by erykoff** [comment]
I don't have MacOS 12 myself, but apparently this is what is returned:
```
$ printf "#include <ciso646>\nint main () {}" | clang -E -stdlib=libc++ -x c++ -dM - | grep _LIBCPP_VERSION

#define _LIBCPP_VERSION 12000
```

Meanwhile, on Monterey as with Big Sur, system clang++ plus homebrew boost are just fine with this test program.  So it's something internal to conda forge.

**Comment by isuruf** [comment]
That's the compile time (SDK) version and not the runtime.

Try doing
```
mamba install "libcxx=12.0.0=*_0" -c conda-forge/label/broken
```

**Comment by timj** [comment]
With `conda-forge/label/broken::libcxx-12.0.0-habf9029_0` the test script works. With `conda-forge::libcxx-12.0.1-habf9029_0` it got a segv.

**Comment by timj** [comment]
Okay. I lied. It also worked before with the other libcxx. It didn't work in the morning. What I did in between was delete my command line tools and install the MacOS12 SDK.

**Comment by erykoff** [comment]
To clarify, it sounds like on Monterey with the MacOS12 SDK then conda forge clang++=12, libcxx=12.0.1 (non broken) work.
But still on Monterey with the MacOS12 SDK then conda forge clang++11, libcxx=11.0.1 seg-fault.

**Comment by timj** [comment]
In fact it seems I'm using 11.1 compilers and 12.0 libcxx and that is working.

**Comment by timj** [comment]
Okay. Turns out that by mistake I was picking up 12.0.0 from main (`libcxx=12.0.0=h2f01273_0`). Using `libcxx=12.0.1=habf9029_0` from conda-forge breaks everything.

**Comment by erykoff** [comment]
Coming back to this ticket, with a summary from what I know now.

First of all, as pointed out by @isuruf on a separate thread, the problem with this _particular_ repro on this ticket is that the compile line is missing the `-L` to get the right library loaded.  So this does work in all cases:
```
clang++ test.cpp -o test -I $CONDA_PREFIX/include $CONDA_PREFIX/lib/libboost_serialization.dylib -Wl,-rpath,$CONDA_PREFIX/lib -L$CONDA_PREFIX/lib
```

The problem that we have been running into with Rubin Science Pipelines in `libc++` version conflicts is actually subtly different.  It's because we had been using `-flat_namespace`.  And it turns out that this _can_ cause conflicts when linking with python, because linking to `libSystem.dylib` on macos always picks up the system cached version of `libc++.dylib`.  So when python is loaded it brings in the system version of the library, and later when an external module is loaded (via `pybind11` in our case) that was linked against the conda version we get strange conflicts.  

Thankfully, with @isuruf's  help we replaced our usage of `-flat_namespace` and that allows these versions to coexist (though I don't exactly understand the _how_ of this).

In the end, the problem is that these slight differences between system and conda forge `libc++` can cause segmentation faults on macos when compiling with `-flat_namespace`, especially when used with python linking.

So I believe we can re-close this issue, and how to prevent these conflicts (or add documentation to specify that conda forge doesn't support `-flat_namespace`) would be a different issue.

**Comment by jakirkham** [comment]
Thanks for the detailed update! Closing as resolved.

**Comment by jcarpent** [comment]
I think the problem persists even with libcxx 14.0.6 (hce7ea42_0). Any suggestion to solve this?

**Comment by jcarpent** [comment]
In fact, the issue is with Boost 1.78, not with the older versions supported by conda-forge.

**Comment by h-vetinari** [comment]
> I think the problem persists even with libcxx 14.0.6 (hce7ea42_0). Any suggestion to solve this?
>
> In fact, the issue is with Boost 1.78, not with the older versions supported by conda-forge.

Can describe the problem in a bit more detail?

**Comment by jcarpent** [comment]
Sorry for the lack of details. If you install in a fresh environment boost=1.78 (`conda install -c conda-forge boost=1.78`) and you compile the initial example:
```cpp
#include <boost/archive/text_oarchive.hpp>
#include <fstream>
#include <string>

int main()
{
  std::string filename = "output.txt";
  std::ofstream ofs(filename.c_str());
  boost::archive::text_oarchive oa(ofs);
  return -1;
}
```
compiled with:
`clang++ test.cpp -o test -I $CONDA_PREFIX/include $CONDA_PREFIX/lib/libboost_serialization.dylib -Wl,-rpath,$CONDA_PREFIX/lib -L$CONDA_PREFIX/lib`
then this is failing.

Is it clear enough?

**Comment by jakirkham** [comment]
Not quite. Could you please share the full environment with `conda list --show-channel-urls`?

**Comment by jcarpent** [comment]
Here it is:
```
# packages in environment at /usr/local/Caskroom/miniconda/base/envs/boost2:
#
# Name                    Version                   Build  Channel
boost                     1.74.0          py310h509978a_5    conda-forge
boost-cpp                 1.74.0               hdbf7018_7    conda-forge
bzip2                     1.0.8                h1de35cc_0    defaults
ca-certificates           2022.6.15            h033912b_0    conda-forge
certifi                   2022.6.15       py310h2ec42d9_0    conda-forge
icu                       69.1                 he49afe7_0    conda-forge
libblas                   3.9.0           15_osx64_openblas    conda-forge
libcblas                  3.9.0           15_osx64_openblas    conda-forge
libcxx                    12.0.0               h2f01273_0    defaults
libffi                    3.3                  hb1e8313_2    defaults
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
liblapack                 3.9.0           15_osx64_openblas    conda-forge
libopenblas               0.3.20          openmp_hb3cd9ec_0    conda-forge
libzlib                   1.2.12               hfe4f2af_2    conda-forge
llvm-openmp               14.0.4               ha654fa7_0    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
ncurses                   6.3                  hca72f7f_3    defaults
numpy                     1.22.1          py310hfbbbacf_0    conda-forge
openssl                   1.1.1q               hfe4f2af_0    conda-forge
pip                       22.1.2          py310hecd8cb5_0    defaults
python                    3.10.4               hdfd78df_0    defaults
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1.2                hca72f7f_1    defaults
setuptools                61.2.0          py310hecd8cb5_0    defaults
sqlite                    3.38.5               h707629a_0    defaults
tk                        8.6.12               h5d9f67b_0    defaults
tzdata                    2022a                hda174b7_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.5                hca72f7f_1    defaults
zlib                      1.2.12               h4dc903c_2    defaults
zstd                      1.5.2                h582d3a0_0    conda-forge
```

**Comment by jakirkham** [comment]
It looks like that is pulling a lot of packages from `defaults`, which is not a supported configuration. Also it appears the `compilers` package is not installed, which would be needed for building. Please try a fresh environment that grabs everything from `conda-forge` and includes the `compilers` package.

**Comment by h-vetinari** [comment]
> Please try a fresh environment that grabs everything from `conda-forge` and includes the `compilers` package.

To ensure you get everything from `conda-forge`, you can do the following (as described in the readme):
```
conda config --add channels conda-forge
conda config --set channel_priority strict
```

**Comment by jcarpent** [comment]
Seems to work perfectly with these key elements. Thanks a lot @jakirkham and @h-vetinari for your helpful advises.
Best,
Justin
