### ISSUE TITLE
latest update breaks mamba entirely

### ISSUE THREAD

**Issue by ngam** [conda-forge/libcxx-feedstock#94]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/mamba-org/mamba/issues/1744
https://github.com/mamba-org/mamba/issues/1743

### Installed packages

```shell
- libcxx   14.0.4  h6a5c8ee_0
+ libcxx   14.0.5  h6a5c8ee_0
```

### Environment info

```shell
n/a
```

**Comment by ngam** [comment]
Probably needs a webpage issue? I will leave that up to you @h-vetinari

**Comment by wolfv** [comment]
Thanks @ngam and @isuruf for the fix!

**Comment by h-vetinari** [comment]
Yes, thanks a lot. Sorry, I was MIA this weekend, just merged some bot PRs and really didn't expect any breakage because this recipe (resp. the LLVM stack) has been pretty stable

**Comment by ngam** [comment]
Thank @isuruf, not me!

I just noticed this when it happened and I thought I would open an issue here immediately in case someone can figure out why it happened (isuruf did!) before it spread to the CI, etc.

I have no idea why it happened, I actually would love a brief explanation if someone has a moment to explain it so that I can learn it 😺

**Comment by isuruf** [comment]
conda-build didn't have a dependency on `cctools` so it was picking up the one from the system and that broke codesigning. Previously we had `cctools` as a dependency in `conda-forge-ci-setup` recipe, but I removed it since that isn't necessary.
